### ISSUE TITLE
Ship Customization Menu

### ISSUE THREAD

**Issue by paraspathak** [paraspathak/Bullet_Hell_Game#7]
Create a customization menu that opens after play click
Add options to select ships and armor
Communicate the choice with game scene

**Comment by paraspathak** [comment]
@braziliger I have added the customization menu that changes the speed and shoot rate of the ship. We also need to figure out which model to use and change that dynamically. Plus two images are also needed ( maybe export from blender?) to add to the ship customization menu. Right now there are two blank white images

**Comment by paraspathak** [comment]
White Ship is added into the game play. It is not working, only ship added and colider. Needs work!

**Comment by braziliger** [comment]
Got this part completed, uploading on my next pull request
also paras i'd like to apologize in advance if i do something stupid with the pull request. i think i have the gist of this now but i will probably find a way to goof it up
